souffle: souffle::TypeEnvironmentAnalysis Class Reference
souffle::TypeEnvironmentAnalysis Class Reference
#include <AstTypeEnvironmentAnalysis.h>
Public Member Functions
const std::set< TypeAttribute > & getPrimitiveTypesInUnion (const AstQualifiedName &identifier) const
const TypeEnvironment & getTypeEnvironment () const
bool isCyclic (const AstQualifiedName &identifier) const
void print (std::ostream &os) const override
print the analysis result in HTML format
void run (const AstTranslationUnit &translationUnit) override
run analysis for a Ast translation unit
TypeEnvironmentAnalysis ()
Public Member Functions inherited from souffle::AstAnalysis
AstAnalysis (std::string identifier)
virtual const std::string & getName () const
get name of the analysis
virtual ~AstAnalysis ()=default
Static Public Attributes
static constexpr const char * name = "type-environment"
Private Member Functions
void analyseCyclicUnions (const Graph< AstQualifiedName > &dependencyGraph, const std::vector< AstType *> &programTypes)
Find cyclic unions.
void analysePrimitiveTypesInUnion (const Graph< AstQualifiedName > &dependencyGraph, const std::vector< AstType *> &programTypes)
Check intersections of unions with primitive types.
Graph< AstQualifiedName > createTypeDependencyGraph (const std::vector< AstType *> &programTypes)
Create a type dependency graph.
void createTypes (const std::vector< AstType *> &program)
Populate Type Environment with Ast Types.
void linkTypes (const std::vector< AstType *> &program)
Link unions and records to their types.
Private Attributes
std::set< AstQualifiedName > cyclicTypes
TypeEnvironment env
std::map< AstQualifiedName, std::set< TypeAttribute > > primitiveTypesInUnions
Additional Inherited Members
Protected Attributes inherited from souffle::AstAnalysis
const std::string identifier
Detailed Description
Definition at line 33 of file AstTypeEnvironmentAnalysis.h.
Constructor & Destructor Documentation
TypeEnvironmentAnalysis()
souffle::TypeEnvironmentAnalysis::TypeEnvironmentAnalysis () inline
Definition at line 37 of file AstTypeEnvironmentAnalysis.h.
References print(), and run().
 : AstAnalysis(name) {}
Member Function Documentation
analyseCyclicUnions()
void souffle::TypeEnvironmentAnalysis::analyseCyclicUnions (const Graph< AstQualifiedName > & dependencyGraph, const std::vector< AstType *> & programTypes) private
Find cyclic unions.
Definition at line 124 of file AstTypeEnvironmentAnalysis.cpp.
References souffle::UnionType::clear(), cyclicTypes, env, souffle::TypeEnvironment::getType(), and souffle::Graph< Vertex, Compare >::reaches().
Referenced by run().
{
     for (const auto& astType : programTypes) {
         auto unionType = dynamic_cast<const AstUnionType*>(astType);
         if (unionType == nullptr) {
             continue;
         }
         AstQualifiedName unionName = unionType->getQualifiedName();
         if (dependencyGraph.reaches(unionName, unionName)) {
             auto& unionType = dynamic_cast<UnionType&>(env.getType(unionName));
             unionType.clear();
             cyclicTypes.insert(std::move(unionName));
         }
     }
 }
analysePrimitiveTypesInUnion()
void souffle::TypeEnvironmentAnalysis::analysePrimitiveTypesInUnion (const Graph< AstQualifiedName > & dependencyGraph, const std::vector< AstType *> & programTypes) private
Check intersections of unions with primitive types.
Definition at line 141 of file AstTypeEnvironmentAnalysis.cpp.
References souffle::Float, primitiveTypesInUnions, souffle::Graph< Vertex, Compare >::reaches(), souffle::Signed, souffle::Symbol, and souffle::Unsigned.
Referenced by run().
{
     for (const auto& astType : programTypes) {
         auto unionType = dynamic_cast<const AstUnionType*>(astType);
         if (unionType == nullptr) {
             continue;
         }
         AstQualifiedName unionName = unionType->getQualifiedName();
         auto iteratorToUnion = primitiveTypesInUnions.find(unionName);
         // Initialize with the empty set
         if (iteratorToUnion == primitiveTypesInUnions.end()) {
             iteratorToUnion = primitiveTypesInUnions.insert({unionName, {}}).first;
         }
         auto& associatedTypes = iteratorToUnion->second;
         // Insert any reachable primitive type
         if (dependencyGraph.reaches(unionName, "number")) {
             associatedTypes.insert(TypeAttribute::Signed);
         }
         if (dependencyGraph.reaches(unionName, "symbol")) {
             associatedTypes.insert(TypeAttribute::Symbol);
         }
         if (dependencyGraph.reaches(unionName, "unsigned")) {
             associatedTypes.insert(TypeAttribute::Unsigned);
         }
         if (dependencyGraph.reaches(unionName, "float")) {
             associatedTypes.insert(TypeAttribute::Float);
         }
     }
 }
createTypeDependencyGraph()
Graph< AstQualifiedName > souffle::TypeEnvironmentAnalysis::createTypeDependencyGraph (const std::vector< AstType *> & programTypes) private
Create a type dependency graph.
Definition at line 90 of file AstTypeEnvironmentAnalysis.cpp.
References souffle::fatal(), souffle::Float, souffle::Graph< Vertex, Compare >::insert(), name, souffle::Record, souffle::Signed, souffle::Symbol, and souffle::Unsigned.
Referenced by run().
{
     Graph<AstQualifiedName> typeDependencyGraph;
     for (const auto* astType : programTypes) {
         if (auto type = dynamic_cast<const AstSubsetType*>(astType)) {
             switch (type->getTypeAttribute()) {
                 case TypeAttribute::Signed:
                     typeDependencyGraph.insert(type->getQualifiedName(), "number");
                     break;
                 case TypeAttribute::Unsigned:
                     typeDependencyGraph.insert(type->getQualifiedName(), "unsigned");
                     break;
                 case TypeAttribute::Float:
                     typeDependencyGraph.insert(type->getQualifiedName(), "float");
                     break;
                 case TypeAttribute::Symbol:
                     typeDependencyGraph.insert(type->getQualifiedName(), "symbol");
                     break;
                 case TypeAttribute::Record:
                     fatal("invalid type");
             }
         } else if (dynamic_cast<const AstRecordType*>(astType) != nullptr) {
             // do nothing
         } else if (auto type = dynamic_cast<const AstUnionType*>(astType)) {
             for (const auto& subtype : type->getTypes()) {
                 typeDependencyGraph.insert(type->getQualifiedName(), subtype);
             }
         } else {
             fatal("unsupported type construct: %s", typeid(astType).name());
         }
     }
     return typeDependencyGraph;
 }
createTypes()
void souffle::TypeEnvironmentAnalysis::createTypes (const std::vector< AstType *> & program) private
Populate Type Environment with Ast Types.
Definition at line 41 of file AstTypeEnvironmentAnalysis.cpp.
References souffle::TypeEnvironment::createSubsetType(), souffle::TypeEnvironment::createType(), env, souffle::fatal(), souffle::TypeEnvironment::isType(), and name.
Referenced by run().
{
     for (const auto* astType : programTypes) {
         // support invalid input with multiple definitions
         if (env.isType(astType->getQualifiedName())) {
             continue;
         }
         if (auto* subType = dynamic_cast<const AstSubsetType*>(astType)) {
             env.createSubsetType(astType->getQualifiedName(), subType->getTypeAttribute());
         } else if (isA<AstUnionType>(*astType)) {
             env.createType<UnionType>(astType->getQualifiedName());
         } else if (isA<AstRecordType>(*astType)) {
             env.createType<RecordType>(astType->getQualifiedName());
         } else {
             fatal("unsupported type construct: %s", typeid(astType).name());
         }
     }
 }
getPrimitiveTypesInUnion()
const std::set<TypeAttribute>& souffle::TypeEnvironmentAnalysis::getPrimitiveTypesInUnion (const AstQualifiedName & identifier) const inline
Definition at line 47 of file AstTypeEnvironmentAnalysis.h.
References primitiveTypesInUnions.
Referenced by souffle::AstSemanticCheckerImpl::checkUnionType().
{
         return primitiveTypesInUnions.at(identifier);
     }
getTypeEnvironment()
const TypeEnvironment& souffle::TypeEnvironmentAnalysis::getTypeEnvironment () const inline
Definition at line 43 of file AstTypeEnvironmentAnalysis.h.
References env.
{
         return env;
     }
isCyclic()
bool souffle::TypeEnvironmentAnalysis::isCyclic (const AstQualifiedName & identifier) const inline
Definition at line 51 of file AstTypeEnvironmentAnalysis.h.
References souffle::contains(), and cyclicTypes.
Referenced by souffle::AstSemanticCheckerImpl::checkUnionType().
{
         return contains(cyclicTypes, identifier);
     }
linkTypes()
void souffle::TypeEnvironmentAnalysis::linkTypes (const std::vector< AstType *> & program) private
Link unions and records to their types.
Definition at line 60 of file AstTypeEnvironmentAnalysis.cpp.
References souffle::UnionType::add(), souffle::RecordType::add(), env, souffle::fatal(), souffle::TypeEnvironment::getType(), souffle::TypeEnvironment::isType(), and name.
Referenced by run().
{
     for (const auto* astType : programTypes) {
         Type& type = env.getType(astType->getQualifiedName());
         if (isA<AstSubsetType>(*astType)) {
             // nothing to do here
         } else if (auto* astUnion = dynamic_cast<const AstUnionType*>(astType)) {
             auto& unionType = dynamic_cast<UnionType&>(type);
             // add element types
             for (const auto& astType : astUnion->getTypes()) {
                 if (env.isType(astType)) {
                     unionType.add(env.getType(astType));
                 }
             }
         } else if (auto* astRecord = dynamic_cast<const AstRecordType*>(astType)) {
             auto& recordType = dynamic_cast<RecordType&>(type);
             // add fields
             for (const auto& field : astRecord->getFields()) {
                 if (env.isType(field.type)) {
                     recordType.add(field.name, env.getType(field.type));
                 }
             }
         } else {
             fatal("unsupported type construct: %s", typeid(astType).name());
         }
     }
 }
print()
void souffle::TypeEnvironmentAnalysis::print (std::ostream &) const override virtual
print the analysis result in HTML format
Reimplemented from souffle::AstAnalysis.
Definition at line 178 of file AstTypeEnvironmentAnalysis.cpp.
References env, and souffle::TypeEnvironment::print().
Referenced by TypeEnvironmentAnalysis().
{
     env.print(os);
 }
run()
void souffle::TypeEnvironmentAnalysis::run (const AstTranslationUnit &) override virtual
run analysis for a Ast translation unit
Implements souffle::AstAnalysis.
Definition at line 28 of file AstTypeEnvironmentAnalysis.cpp.
References analyseCyclicUnions(), analysePrimitiveTypesInUnion(), createTypeDependencyGraph(), createTypes(), souffle::AstTranslationUnit::getProgram(), souffle::AstProgram::getTypes(), and linkTypes().
Referenced by TypeEnvironmentAnalysis().
{
     const AstProgram& program = *translationUnit.getProgram();
     std::vector<AstType*> programTypes = program.getTypes();
     createTypes(programTypes);
     linkTypes(programTypes);
     Graph<AstQualifiedName> typeDependencyGraph{createTypeDependencyGraph(programTypes)};
     analyseCyclicUnions(typeDependencyGraph, programTypes);
     analysePrimitiveTypesInUnion(typeDependencyGraph, programTypes);
 }
Field Documentation
cyclicTypes
std::set<AstQualifiedName> souffle::TypeEnvironmentAnalysis::cyclicTypes private
Definition at line 58 of file AstTypeEnvironmentAnalysis.h.
Referenced by analyseCyclicUnions(), and isCyclic().
env
TypeEnvironment souffle::TypeEnvironmentAnalysis::env private
Definition at line 56 of file AstTypeEnvironmentAnalysis.h.
Referenced by analyseCyclicUnions(), createTypes(), getTypeEnvironment(), linkTypes(), and print().
name
constexpr const char* souffle::TypeEnvironmentAnalysis::name = "type-environment" static
Definition at line 35 of file AstTypeEnvironmentAnalysis.h.
Referenced by createTypeDependencyGraph(), createTypes(), and linkTypes().
primitiveTypesInUnions
std::map<AstQualifiedName, std::set<TypeAttribute> > souffle::TypeEnvironmentAnalysis::primitiveTypesInUnions private
Definition at line 57 of file AstTypeEnvironmentAnalysis.h.
Referenced by analysePrimitiveTypesInUnion(), and getPrimitiveTypesInUnion().
The documentation for this class was generated from the following files:
AstTypeEnvironmentAnalysis.h
AstTypeEnvironmentAnalysis.cpp